### ISSUE TITLE
Enable logging in next release of opentelemetry-cpp

### ISSUE THREAD

**Issue by johanpel** [conda-forge/cpp-opentelemetry-sdk-feedstock#13]
### Comment:

In the current release of opentelemetry-cpp (v1.2.0) there is an option to enable the experimental logging feature through the `WITH_LOGS_PREVIEW` CMake option. It's not enabled at the moment.

For users of the package, it looks like this functionality will only be exposed when using the `ENABLE_LOGS_PREVIEW` compile definition. 

I'm not sure when this feature will leave its experimental status, and I'm not in a terrible hurry to use it. But, regardless of what it looks like in the next release, it would be nice if we could enable it, or whenever we have a reason to make a new Conda package build.

(If something I said here doesn't make sense, please correct me - I'm not very familiar with the Conda ecosystem yet.)

**Comment by lidavidm** [comment]
v1.3.0 just got released so I'll try to remember that. That said it seems metrics is getting more attention than logs at the moment.

**Comment by johanpel** [comment]
Thanks for enabling the preview!
