### ISSUE TITLE
Should we build with STL and/or ABSEIL support?

### ISSUE THREAD

**Issue by kkraus14** [conda-forge/cpp-opentelemetry-sdk-feedstock#29]
### Comment:

Looks like we're currently not building with STL or Abseil support. At least enabling STL would be an ABI break so we should probably wait until a patch version to prevent breaking folks if we want to enable it.

See:
* abseil: https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.6.0/api/CMakeLists.txt#L44
* STL: https://github.com/open-telemetry/opentelemetry-cpp/blob/v1.6.0/api/CMakeLists.txt#L55

**Comment by h-vetinari** [comment]
We can probably build with abseil and get two bird with one stone (since on C++17, abseil will already mostly use STL for its types).

**Comment by kkraus14** [comment]
> We can probably build with abseil and get two bird with one stone (since on C++17, abseil will already mostly use STL for its types).

Abseil is a non-trivial dependency with less than ideal versioning where I'd be -1 on making that the default build.

**Comment by h-vetinari** [comment]
Meh, it's already everywhere (including now protobuf's API). 🤷 

Especially as I expect most users of this lib to come through arrow, which already depends on abseil.

**Comment by h-vetinari** [comment]
> Abseil is a non-trivial dependency with less than ideal versioning where I'd be -1 on making that the default build.

As of #48, opentelemetry will depend on abseil (through protobuf 4.x), so this point is moot. Not sure if we gain anything by flipping `WITH_ABSEIL` though? CC @lidavidm

**Comment by lidavidm** [comment]
Yeah, and additionally they've said upstream that C++17 support effectively requires WITH_STL.

From a quick search, the flag still configures whether it tries to link some abseil libraries into OTel. But it's overridden in the source itself via ifdefs, so I say it's a pointless flag and we just use WITH_STL. 

(Also, if you don't use WITH_STL and don't use WITH_ABSEIL, it just pulls a vendored copy anyways. :facepalm:)
